USER_LIB_PATH = /home/johann/Arduino/libs/
ARDUINO_LIBS = HX711 avr_uart avr-i2c-slave

BOARD_TAG    = nano
MONITOR_PORT = /dev/ttyUSB0
#BOARD_TAG    = uno
#MONITOR_PORT = /dev/ttyACM0

CFLAGS = -g -Os -std=gnu99
LDFLAGS = -Wl,-u,vfprintf -lprintf_flt

ARDMK_VENDOR=archlinux-arduino
include /home/johann/Arduino/Arduino-Makefile/Arduino.mk


