#USER_LIB_PATH = /home/johann/Arduino/libs/
ARDUINO_LIBS = Wire

BOARD_TAG    = nano
BOARD_SUB    = atmega328
# Needed with older bootloader
AVRDUDE_ARD_BAUDRATE = 57600

# Specify AVR architecture (flag from platformio for compatibilty)
CFLAGS       = -DARDUINO_ARCH_AVR

# MONITOR_PORT = /dev/ttyACM0
MONITOR_PORT = /dev/ttyUSB0

ARCHITECTURE  = avr
ARDMK_VENDOR  = archlinux-arduino
include /usr/share/arduino/Arduino.mk
