#USER_LIB_PATH = /home/johann/Arduino/libs/
ARDUINO_LIBS = Wire

BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0

ARDMK_VENDOR=archlinux-arduino
include /home/johann/Arduino/Arduino-Makefile/Arduino.mk
